### PR TITLE
added syntax support

### PR DESCRIPTION
**Pull request by asrmapro**
Hello, I'm new at coding and do it as a side hobby, so I'm sorry if I am going about this the wrong way. I really appreciate your extension and noticed you were interested in not having a dependency for syntax highlighting.

The fish shell syntax grammars I've seen as vscode extensions have been based almost entirely on Leonard Chin's 2004 tmLanguage file (https://github.com/l15n/fish-tmbundle). Mine is largely based on Phidica Veia's 2017 YAML-tmLanguage file (https://github.com/Phidica/sublime-fish), with a few changes and additions of my own. I also incorporated some of the ideas from Leonard Chin's file.

You're welcome to use anything in my repository (https://github.com/asrmapro/vscode-fish-shell-syntax) which includes the source YAML-tmLanguage file (not included in this pull request). I found using YAML made things easier since both the plist tmLanguage and the corresponding JSON-tmLanguage files have a lot of escapes that make the regex a lot harder for me to read.

Anyway, this is my first repo, first pull request, etc. so let me know what you think.

### CODE REVIEW

**Comment by lunaryorn** [comment]
Wow thank you very much! 🙏. That’s great work and I’ll definitely add it.  I only briefly ran over your changes and your repo and it’s waaaaay better than the other fish syntaxes for VSCode 👍

I’ll take deeper look but I probably won’t get to it before the next weekend—got a lot to do currently.  I hope I don’t forget; if you don’t hear anything from me until next weekend please send me a little reminder 😊

**Comment by asrmapro** [comment]
Hey, thanks so much for your kind feedback! Of course, all due credit to Phidica and Leonard as to why it's better, and I'm glad you agree.

No worries at all about waiting until next weekend, and I will follow up with you with a reminder.

Also, since you obviously have a lot more programming experience than I do, when you do get a chance to look at it in more detail, any and all feedback would be welcome and of course you are welcome to make any changes at all. (I don't plan to release this as a separate extension if you decide to incorporate it into yours -- think everyone would benefit from less fragmentation.)

Thanks again for your quick reply and for your help!

**Comment by lunaryorn** [comment]
@asrmapro Sorry to get back so late.  I now took a look at the code, and I like it.  Your repository is perfectly fine to publish as an extension 👍  But you said you'd rather like to merge your grammar into this repository, which makes me very happy 😊 

But I think I'd like to see a couple of further changes in this pull request.  As far as I understand the `.json` file is not the actual grammar, is it?  It looks like it's generated from the YAML file?

In this case I'd prefer if we added the YAML file to the repository instead, and never even committed the `.json` file, just like we don't commit the `.js` file that the typescript compiler generates.  We should extend `vsce:prepublish` to not only compile typescript but also generate the final JSON grammar from the YAML file.

I'm not very familiar with Javascript's approach here, but I think we could add a `Gulpfile` that builds typescript and generates the JSON grammar, and use that as prepublish task.

Alternatively we could convert the YAML grammar to JSON once and for all, and continue to use the latter as definitive source, but then we should convert to a readable JSON file, and attempt to retain the comments in the original YAML file (might not be possible tho).

Which way would you like to go?

**Comment by lunaryorn** [comment]
I'm closing this due to the lack of activity.

**Pull request closed without merging**
